services:

  db:
    image: postgres:alpine
    hostname: db
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1